# Generated by Django 5.1.6 on 2025-05-19 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_answer_answer_content_alter_answer_ask_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="document",
            name="document",
            field=models.FileField(upload_to="documents/"),
        ),
        migrations.CreateModel(
            name="ProcessedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("text_content", models.TextField()),
                ("embeddings", models.BinaryField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.document",
                    ),
                ),
            ],
        ),
    ]
