# Generated by Django 5.0.6 on 2025-11-28 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_document_is_processed_alter_document_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-ask_at'], 'verbose_name': 'Câu hỏi & Trả lời', 'verbose_name_plural': 'Câu hỏi & Trả lời'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Tài liệu', 'verbose_name_plural': 'Tài liệu'},
        ),
        migrations.AlterModelOptions(
            name='processeddocument',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Tài liệu đã xử lý', 'verbose_name_plural': 'Tài liệu đã xử lý'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời gian trả lời'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_content',
            field=models.TextField(help_text='Nội dung câu trả lời'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ask_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời gian hỏi'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ask_content',
            field=models.TextField(help_text='Nội dung câu hỏi'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User đặt câu hỏi', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='answer',
            name='uploaded_file',
            field=models.FileField(blank=True, help_text='File được tham chiếu (optional)', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, help_text='Mô tả tài liệu', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(help_text='File PDF', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Đã xử lý (trích xuất, embedding)?'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời gian upload'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User upload', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Liên kết tài liệu gốc', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.document'),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='embeddings',
            field=models.BinaryField(blank=True, help_text='Embeddings (pickle numpy array)', null=True),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='file_name',
            field=models.CharField(help_text='Tên file gốc', max_length=255),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='text_content',
            field=models.TextField(help_text='Nội dung văn bản đã trích xuất'),
        ),
        migrations.AlterField(
            model_name='processeddocument',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Thời gian xử lý'),
        ),
    ]
