# Generated by Django 5.0.6 on 2025-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_answer_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='context',
            field=models.TextField(blank=True, help_text='Context (chunks liên quan) được dùng để tạo câu trả lời', null=True),
        ),
    ]
